repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ '--maxkb=1000' ]
      - id: detect-private-key
      - id: mixed-line-ending
        args: [ '--fix=lf' ]

  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check
        entry: gradlew.bat spotlessCheck
        language: script
        types: [ java ]
        pass_filenames: false
        stages: [ pre-commit ]

      - id: gradle-test
        name: Run Unit Tests
        entry: gradlew.bat test
        language: script
        types: [ java ]
        pass_filenames: false
        stages: [ pre-commit ]

      - id: gradle-compile
        name: Gradle Compile
        entry: gradlew.bat compileJava compileTestJava
        language: script
        types: [ java ]
        pass_filenames: false
        stages: [ pre-commit ]
