pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = "socially-backend"

include("app")
include("commons:observability")
include("commons:kernel:domain")
include("auth:kernel:domain")
include("auth:kernel:infrastructure:left")
include("auth:kernel:infrastructure:right")
include("auth:login:application")
include("auth:login:infrastructure:left")
include("auth:callback:domain")
include("auth:callback:application")
include("auth:callback:infrastructure:left")
include("auth:callback:infrastructure:right")
include("auth:me:application")
include("auth:me:infrastructure:left")
include("auth:logout:domain")
include("auth:logout:application")
include("auth:logout:infrastructure:left")
include("auth:logout:infrastructure:right")
include("auth:refresh:domain")
include("auth:refresh:application")
include("auth:refresh:infrastructure:left")
include("auth:refresh:infrastructure:right")
include("donor:kernel:domain")
include("donor:kernel:infrastructure:right")
include("donor:create:domain")
include("donor:create:application")
include("donor:create:infrastructure:right")
include("donor:find-by-user-id:domain")
include("donor:find-by-user-id:application")
include("donor:find-by-user-id:infrastructure:right")
include("donor:find-by-id:domain")
include("donor:find-by-id:application")
include("donor:find-by-id:infrastructure:right")
include("donation:kernel:domain")
include("donation:kernel:infrastructure:right")
include("donation:create:domain")
include("donation:create:application")
include("donation:create:infrastructure:left")
include("donation:create:infrastructure:right")
include("donation:delete:domain")
include("donation:delete:application")
include("donation:delete:infrastructure:left")
include("donation:delete:infrastructure:right")
include("donation:get-by-id:domain")
include("donation:get-by-id:application")
include("donation:get-by-id:infrastructure:left")
include("donation:get-by-id:infrastructure:right")
include("donation:update:domain")
include("donation:update:application")
include("donation:update:infrastructure:left")
include("donation:update:infrastructure:right")
include("donation:find:domain")
include("donation:find:application")
include("donation:find:infrastructure:left")
include("donation:find:infrastructure:right")
include("user:kernel:domain")
include("user:kernel:infrastructure:right")
include("user:create:domain")
include("user:create:application")
include("user:create:infrastructure:right")
include("user:find-by-email:domain")
include("user:find-by-email:application")
include("user:find-by-email:infrastructure:right")
include("user:find-by-federated-identity:domain")
include("user:find-by-federated-identity:application")
include("user:find-by-federated-identity:infrastructure:right")
include("user:federated-identity:link:domain")
include("user:federated-identity:link:application")
include("user:federated-identity:link:infrastructure:right")
include("user:update-profile:domain")
include("user:update-profile:application")
include("user:update-profile:infrastructure:right")
