spring:
  application:
    name: socially-backend
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

auth:
  cookies:
    names:
      refresh: socially_refresh_token
      state: socially_oauth_state
      pkce: socially_oauth_pkce
