name: Continuous Integration

run-name: ${{ github.event_name == 'workflow_dispatch' && format('Continuous Integration @ {0}', inputs.environment) || '' }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - dev
        default: dev
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  snyk-scan:
    name: Pre-checks
    uses: ./.github/workflows/_snyk-scan.yaml
    secrets: inherit

  sonar-scan:
    name: Pre-checks
    uses: ./.github/workflows/_sonar-scan.yaml
    secrets: inherit

  build:
    name: Image
    uses: ./.github/workflows/_build-image.yaml
    with:
      environment: ${{ (github.event_name == 'workflow_dispatch' && inputs.environment) || 'dev' }}

  push:
    name: Image
    needs: [ snyk-scan, sonar-scan, build ]
    uses: ./.github/workflows/_push-image.yaml
    with:
      environment: ${{ (github.event_name == 'workflow_dispatch' && inputs.environment) || 'dev' }}
      artifact_name: ${{ needs.build.outputs.image_artifact_name }}

  deploy:
    name: Image
    needs: [ push ]
    uses: ./.github/workflows/_deploy-image.yaml
    with:
      environment: ${{ (github.event_name == 'workflow_dispatch' && inputs.environment) || 'dev' }}
      image_uri: ${{ needs.push.outputs.image_uri }}
      image_tag: ${{ needs.push.outputs.image_tag }}
