name: Push image to ECR

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
        description: "Name of the JAR artifact to download"
      image_tag:
        required: true
        type: string
        description: "Tag for the Docker image"
    secrets:
      aws_account_id:
        required: true
        description: "AWS Account ID for ECR"

jobs:
  push:
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.login-ecr.outputs.registry }}/socially-dev-service:${{ inputs.image_tag }}
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-south-2
          role-to-assume: arn:aws:iam::980834360715:role/github-agent-ecr

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image to Amazon ECR
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          push: true
          tags: ${{ env.ECR_REGISTRY }}/socially-dev-service:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
